### ISSUE TITLE
POST HERE IF YOU THINK THERE'S STOLEN CODE

### ISSUE THREAD

**Issue by aerothan** [nosnowowie93347/Terrabot#1]
This is a straight copy of corpbot from corpnewt. Stop copying others code and claiming it as your own.

**Comment by nosnowowie93347** [comment]
I will be sure to remove anything that's taken from other repositories/projects.

**Comment by nosnowowie93347** [comment]
done. Any files from corpbot have been removed.

Read updated README file for more info.
