### ISSUE TITLE
Music not working

### ISSUE THREAD

**Issue by SukuyaZ** [nosnowowie93347/Terrabot#2]
The music commands are not working. You need to spend more time fixing your bot.

**Comment by nosnowowie93347** [comment]
Ah right that's the other thing I was gonna fix. I'll get to work

**Comment by nosnowowie93347** [comment]
Music can be very complicated. I'm doing a bit of research on that.

**Comment by nosnowowie93347** [comment]
@SukuyaZ music should be back up and running.

**Comment by nosnowowie93347** [comment]
Open a new issue I'd it's still messed up
