### ISSUE TITLE
Issue with Heroku

### ISSUE THREAD

**Issue by LunaVM** [nosnowowie93347/Terrabot#3]
The page https://terrabot-bot.herokuapp.com/ does not load.

**Comment by nosnowowie93347** [comment]
Yeah idk how heroku works. I'll look into it

**Comment by LunaVM** [comment]
I dont trust you. Take a look at it by 9PM TODAY!!!!!!

**Comment by nosnowowie93347** [comment]
Yep

**Comment by nosnowowie93347** [comment]
Alright Terrabot is now hosted with Heroku. The link doesn't work because it's not supposed to. Heroku just makes sure the bot stays online
